TWE-7 - BE - Division page
torchbox/torchbox.com pull request #324
Opened 2024-12-19 12:30 UTC by SharmaineLim

[Link to Ticket](https://torchbox.atlassian.net/browse/TWE-7)

### Description of Changes Made

- Add the new Division page BE

### How to Test

### Screenshots

<details>
  <summary>Expand to see more</summary>

</details>

### MR Checklist

- [ ] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [ ] Stay on point and keep it small so the merge request can be easily reviewed.
- [ ] Tests and linting passes.

#### Unit tests

- [x] Added
- [ ] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (See https://intranet.torchbox.com/torchbox-com-project-docs for the private link, for Torchbox employees only)
- [ ] Updated field spec (See https://intranet.torchbox.com/torchbox-com-project-docs for the private link, for Torchbox employees only)
- [ ] Not required

#### Browser testing

- [ ] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
  - Latest version of Firefox on mac
  - Latest version of Safari on mac
  - Safari on last two versions of iOS
  - Chrome on last two versions of Android
- [x] Not required

#### Data protection

- [x] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Light and dark mode

- [ ] I have tested the changes in both light and dark mode
- [x] The change is not relevant to dark and light mode

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] HTML validation passes
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [ ] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [x] Changes are not relevant the pattern library

2024-12-20 07:55 UTC, SharmaineLim commented on pyproject.toml
> +faker = "^24.11.0"
Added as explicit dependencies since we use them.

2025-01-10 15:16 UTC, zerolab requested changes
Left a few questions and suggestions. Love the use of factoryboy post generation features.

I am missing the wider project context -- what about the blocks under partner logos ("what we do", "beliefs", "sparks & kindling", "lighting little fires")?

2025-01-10 15:16 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/_pattern_library_only/streamfield/division_story_container.html
> +
```suggestion
```

2025-01-10 15:16 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/molecules/streamfield/stream_block_division.html
> +{% endif %}
question: should we not just use `templates/patterns/molecules/streamfield/stream_block.html` for all Streamfields?

I see a number of templates with the same content. It may well be it is a project convention

2025-01-13 08:27 UTC, SharmaineLim commented on tbx/core/blocks.py
> +        help_text=_(
I added gettext because I saw another file was using it, but I guess if we've never translated the site after all these years, we aren't likely to start anytime soon. I'll remove the gettext.

2025-01-13 08:43 UTC, SharmaineLim commented on tbx/project_styleguide/templates/patterns/molecules/streamfield/stream_block_division.html
> +{% endif %}
I think I'll drop `stream_block_division.html` and let the page YAML access the story container directly like I did in #335 because this pattern of having a stream_block_division.html just to link division_page.html to division_story_container.html doesn't really make sense to me.

2025-01-13 09:22 UTC, SharmaineLim commented on tbx/project_styleguide/templates/patterns/_pattern_library_only/streamfield/division_story_container.html
> +
Done in [60249d2](https://github.com/torchbox/torchbox.com/pull/324/commits/60249d24b02626e7005f1e96d2218144a1c714fd)

2025-01-13 09:24 UTC, SharmaineLim commented on pyproject.toml
> +faker = "^24.11.0"
I'd been burned before by not making something an explicit dependency despite it being used in the code 😅

2025-01-13 09:27 UTC, SharmaineLim commented
> I am missing the wider project context -- what about the blocks under partner logos ("what we do", "beliefs", "sparks & kindling", "lighting little fires")?

Ah sorry, those are covered by other tickets 😄 Thanks for checking! And thank you for the review~

2025-01-13 10:30 UTC, zerolab commented on tbx/project_styleguide/templates/patterns/_pattern_library_only/streamfield/division_story_container.html
> +{% include "patterns/molecules/streamfield/blocks/introduction_with_images_block.html" %}
q: should this not have four_photo_collage and partners_block too?

2025-01-13 10:36 UTC, SharmaineLim commented on tbx/project_styleguide/templates/patterns/_pattern_library_only/streamfield/division_story_container.html
> +{% include "patterns/molecules/streamfield/blocks/introduction_with_images_block.html" %}
That's a good shout.

My initial thought was to not have the four photo collage block because it was the alternative for the introduction, but it can't hurt to have it. Not sure how I missed adding the partners block too.

Done in [7d82a84](https://github.com/torchbox/torchbox.com/pull/324/commits/7d82a84d16e8c3a972540e2f49d0f5d2c8c649c9)

2025-01-15 07:21 UTC, merged